# Generated by Django 5.2.7 on 2025-11-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_jobs', 'Can create walking jobs'), ('can_manage_dogs', 'Can manage dogs')],
            },
        ),
        migrations.CreateModel(
            name='Doggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=0.0)),
                ('age', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userbase.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_accept_jobs', 'Can accept walking jobs'), ('can_complete_jobs', 'Can mark jobs as completed')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '1 hour')], default='30', max_length=3)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('recurrence', models.CharField(choices=[('NONE', 'No recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbase.doggy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbase.owner')),
                ('walker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userbase.walker')),
            ],
        ),
    ]
