# Generated by Django 5.2.7 on 2025-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '1 hour')], default='30', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'No recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
