# Generated by Django 5.2.7 on 2025-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userbase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walker",
            name="energy_level",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="walker",
            name="temperament",
            field=models.CharField(
                choices=[
                    ("FRIENDLY", "Friendly"),
                    ("SHY", "Shy"),
                    ("ENERGETIC", "Energetic"),
                    ("CALM", "Calm"),
                    ("PROTECTIVE", "Protective"),
                    ("PLAYFUL", "Playful"),
                    ("INDEPENDENT", "Independent"),
                    ("SOCIAL", "Social"),
                ],
                default="FRIENDLY",
                max_length=20,
            ),
        ),
    ]
