# Generated by Django 5.2.7 on 2025-11-08 02:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggy',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doggy',
            name='photo',
            field=models.ImageField(blank=True, default='dog_photos/default_paw.png', null=True, upload_to='dog_photos/'),
        ),
        migrations.AddField(
            model_name='doggy',
            name='temperament',
            field=models.JSONField(default={'aggressive': False, 'anxious': False, 'friendly': False, 'lazy': False, 'obedient': False, 'playful': False, 'protective': False, 'shy': False, 'vocal': False}),
        ),
        migrations.AlterField(
            model_name='doggy',
            name='age',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)]),
        ),
        migrations.AlterField(
            model_name='doggy',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(350.0)]),
        ),
    ]
