# Generated by Django 5.2.7 on 2025-11-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='energy_level',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='walker',
            name='temperament',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='walker',
            name='weight_range',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
