# Generated by Django 5.2.7 on 2025-11-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0002_owner_remove_doggy_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'permissions': [('', '')]},
        ),
        migrations.AlterModelOptions(
            name='walker',
            options={'permissions': [('', '')]},
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='walker',
            name='name',
        ),
        migrations.AddField(
            model_name='doggy',
            name='age',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doggy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userbase.owner'),
        ),
        migrations.AddField(
            model_name='doggy',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbase.doggy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbase.owner')),
                ('walker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userbase.walker')),
            ],
        ),
    ]
