# Generated by Django 5.2.7 on 2025-11-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        ('userbase', '0002_doggy_breed_doggy_photo_doggy_temperament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doggy',
            name='temperament',
        ),
        migrations.AddField(
            model_name='doggy',
            name='temperaments',
            field=models.ManyToManyField(to='dogs.temperament'),
        ),
    ]
