# Generated by Django 5.2.7 on 2025-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0003_alter_owner_options_alter_walker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
