# Generated by Django 5.2.7 on 2025-11-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userbase", "0004_alter_owner_user_alter_walker_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doggy",
            name="temperaments",
        ),
        migrations.AddField(
            model_name="doggy",
            name="temper",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LAZY", "Lazy"),
                    ("AGGRESSIVE", "Aggressive"),
                    ("MEEK", "Meek"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="walker",
            name="temper",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("LAZY", "Lazy"),
                    ("AGGRESSIVE", "Aggressive"),
                    ("MEEK", "Meek"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
