# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from conftest import get_driver

class TestWalkerAccountDeletion():
  def setup_method(self, method):
    # Get browser from command line argument (default: chrome)
    self.driver = get_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_walkerAccountDeletion(self):
    # Determine base URL
    base_url = os.getenv('TEST_URL', 'http://ec2-18.191.170.51.us-east-1.compute.amazonaws.com:8000')
    self.driver.get(f"{base_url}/")
    self.driver.set_window_size(990, 1068)
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.LINK_TEXT, "Login"))
    ).click()
    self.driver.find_element(By.ID, "id_username").send_keys("Walker")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//a[contains(@href, 'settings') or contains(@href, 'edit')]"))
    ).click()
    try:
        edit_link = WebDriverWait(self.driver, 5).until(
            EC.element_to_be_clickable((By.XPATH, "//a[contains(@href, 'edit')]"))
        )
        edit_link.click()
    except:
        pass  # Already on edit page
    delete_btn = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.ID, "delete-account-btn"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", delete_btn)
    time.sleep(0.5)
    delete_btn.click()
    time.sleep(0.5)
    try:
        WebDriverWait(self.driver, 5).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        alert.accept()
        time.sleep(0.5)
    except:
        pass
    
