# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDogediting():
  def setup_method(self, method):
    options = Options()
    if os.getenv('HEADLESS', '').lower() in ('true', '1', 'yes'):
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dogediting(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(990, 1068)
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .card-body").click()
    # Hover over the dog card to reveal the overlay
    dog_card = self.driver.find_element(By.CSS_SELECTOR, ".dog-card")
    actions = ActionChains(self.driver)
    actions.move_to_element(dog_card).perform()
    time.sleep(1)  # give time for hover effects to reveal the Edit link
    # Click the Edit button in the overlay
    self.driver.find_element(By.CSS_SELECTOR, ".edit-btn").click()
    self.driver.find_element(By.ID, "id_age").clear()
    self.driver.find_element(By.ID, "id_age").send_keys("5")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Stroll").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .card-title").click()
    # Hover over the dog card to reveal the overlay
    dog_card = self.driver.find_element(By.CSS_SELECTOR, ".dog-card")
    actions = ActionChains(self.driver)
    actions.move_to_element(dog_card).perform()
    time.sleep(1)  # give time for hover effects to reveal the Edit link
    # Click the Edit button in the overlay
    self.driver.find_element(By.CSS_SELECTOR, ".edit-btn").click()
