# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOwnerDogCreation():
  def setup_method(self, method):
    options = Options()
    if os.getenv('HEADLESS', '').lower() in ('true', '1', 'yes'):
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ownerDogCreation(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(990, 1068)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Stroll").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dogs").click()
    self.driver.find_element(By.LINK_TEXT, "Add New Dog").click()
    self.driver.find_element(By.ID, "id_dog_name").click()
    self.driver.find_element(By.ID, "id_dog_name").send_keys("Carl")
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    self.driver.find_element(By.ID, "id_breed").click()
    self.driver.find_element(By.ID, "id_breed").send_keys("Carl")
    self.driver.find_element(By.ID, "id_age").send_keys("2")
    self.driver.find_element(By.ID, "id_temperament").click()
    dropdown = self.driver.find_element(By.ID, "id_temperament")
    dropdown.find_element(By.XPATH, "//option[. = 'Shy']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_temperament > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_energy_level").click()
    dropdown = self.driver.find_element(By.ID, "id_energy_level")
    dropdown.find_element(By.XPATH, "//option[. = 'Low']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_energy_level > option:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_weight").click()
    element = self.driver.find_element(By.ID, "id_weight")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "id_weight")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "id_weight")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "id_weight").clear()
    self.driver.find_element(By.ID, "id_weight").click()
    self.driver.find_element(By.ID, "id_weight").send_keys("10")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
