# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from conftest import get_driver

class TestOwnerJobCreation():
  def setup_method(self, method):
    # Get browser from command line argument (default: chrome)
    self.driver = get_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ownerJobCreation(self):
    self.driver.get("http://ec2-18.191.170.51.us-east-1.compute.amazonaws.com:8000/")
    self.driver.set_window_size(990, 1068)
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .card-title").click()
    self.driver.find_element(By.LINK_TEXT, "+ Create Job").click()
    self.driver.find_element(By.ID, "id_title").click()
    self.driver.find_element(By.ID, "id_title").send_keys("New Job!")
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("This is a test job that contains a dog outside of the filters!")
    dropdown = self.driver.find_element(By.ID, "id_dog")
    dropdown.find_element(By.XPATH, "//option[. = 'Carl']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_dog > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "id_scheduled_date").click()
    self.driver.find_element(By.ID, "id_scheduled_date").send_keys("2025-12-08")
    self.driver.find_element(By.ID, "id_scheduled_time").click()
    self.driver.find_element(By.ID, "id_scheduled_time").send_keys("10:10")
    self.driver.find_element(By.ID, "id_location").click()
    self.driver.find_element(By.ID, "id_location").send_keys("UNO")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
