# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOwnerAccountDeletion():
  def setup_method(self, method):
    options = Options()
    if os.getenv('HEADLESS', '').lower() in ('true', '1', 'yes'):
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ownerAccountDeletion(self):
    # Determine base URL
    base_url = os.getenv('TEST_URL', 'http://localhost:8000')
    self.driver.get(f"{base_url}/")
    self.driver.set_window_size(990, 1068)
    
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    
    WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.LINK_TEXT, "Login"))
    ).click()
    
    # Login as Owner
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    
    # Navigate to edit profile - check if navbar toggler is displayed
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    
    # Click on settings/profile link
    WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//a[contains(@href, 'settings') or contains(@href, 'edit')]"))
    ).click()
    
    # If we're on settings page, click edit profile
    try:
        edit_link = WebDriverWait(self.driver, 5).until(
            EC.element_to_be_clickable((By.XPATH, "//a[contains(@href, 'edit')]"))
        )
        edit_link.click()
    except:
        pass  # Already on edit page
    
    # Wait for delete account button and scroll to it
    delete_btn = WebDriverWait(self.driver, 10).until(
        EC.presence_of_element_located((By.ID, "delete-account-btn"))
    )
    self.driver.execute_script("arguments[0].scrollIntoView(true);", delete_btn)
    time.sleep(0.5)
    
    # Click delete account button - this will trigger JavaScript confirm dialogs
    delete_btn.click()
    time.sleep(0.5)
    
    # Handle first confirmation dialog
    try:
        WebDriverWait(self.driver, 5).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        alert.accept()  # First confirmation
        time.sleep(0.5)
    except:
        pass
    
    # Handle second confirmation dialog
    try:
        WebDriverWait(self.driver, 5).until(EC.alert_is_present())
        alert = self.driver.switch_to.alert
        alert.accept()  # Second confirmation
        time.sleep(1)
    except:
        pass
  
