# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJobDeletion():
  def setup_method(self, method):
    options = Options()
    if os.getenv('HEADLESS', '').lower() in ('true', '1', 'yes'):
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_jobDeletion(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(990, 1068)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_password").send_keys("strongpassword")
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .card-body").click()
    # Wait for job list page to load
    time.sleep(1)
    # Find the delete button for a job (second job if available, otherwise first)
    delete_buttons = self.driver.find_elements(By.LINK_TEXT, "Delete Job")
    if len(delete_buttons) > 1:
        delete_buttons[1].click()
    elif len(delete_buttons) == 1:
        delete_buttons[0].click()
    else:
        # Fallback: try CSS selector
        self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.LINK_TEXT, "Stroll").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) .card-title").click()
  
