# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from conftest import get_driver

class TestWalkerAccountCreation():
  def setup_method(self, method):
    # Get browser from command line argument (default: chrome)
    self.driver = get_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_walkerAccountCreation(self):
    self.driver.get("http://ec2-18.191.170.51.us-east-1.compute.amazonaws.com:8000/")
    self.driver.set_window_size(990, 1068)
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Walker")
    self.driver.find_element(By.ID, "id_email").send_keys("walker@mailus.com")
    self.driver.find_element(By.ID, "id_password1").send_keys("strongpassword")
    self.driver.find_element(By.ID, "id_password2").send_keys("strongpassword")
    self.driver.find_element(By.ID, "id_is_owner").click()
    self.driver.find_element(By.ID, "id_address").click()
    self.driver.find_element(By.ID, "id_is_owner").click()
    self.driver.find_element(By.ID, "id_is_walker").click()
    self.driver.find_element(By.ID, "id_bio").click()
    self.driver.find_element(By.ID, "id_bio").send_keys("This guy walks dogs lol")
    self.driver.find_element(By.CSS_SELECTOR, ".walker-card .mb-3:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_temperament_1").click()
    self.driver.find_element(By.ID, "id_temperament_2").click()
    self.driver.find_element(By.ID, "id_temperament_3").click()
    self.driver.find_element(By.ID, "id_energy_level_1").click()
    self.driver.find_element(By.ID, "id_energy_level_2").click()
    self.driver.find_element(By.ID, "id_temperament_3").click()
    self.driver.find_element(By.ID, "id_temperament_1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_temperament > div:nth-child(1) > label").click()
    self.driver.find_element(By.ID, "id_temperament_5").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(8) > label").click()
    self.driver.find_element(By.ID, "id_weight_range_2").click()
    self.driver.find_element(By.ID, "id_weight_range_1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
