# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOwnerAccountCreation():
  def setup_method(self, method):
    options = Options()
    if os.getenv('HEADLESS', '').lower() in ('true', '1', 'yes'):
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ownerAccountCreation(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(990, 1068)
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("Owner")
    self.driver.find_element(By.ID, "id_email").send_keys("owners@mailus.com")
    self.driver.find_element(By.ID, "id_password1").send_keys("strongpassword")
    self.driver.find_element(By.ID, "id_password2").send_keys("strongpassword")
    self.driver.find_element(By.ID, "id_is_owner").click()
    self.driver.find_element(By.ID, "id_address").click()
    self.driver.find_element(By.ID, "id_address").send_keys("14442 Pacific st.")
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").send_keys("4022223333")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # Check if navbar toggler is displayed before clicking
    try:
        toggler = self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler")
        if toggler.is_displayed():
            toggler.click()
            time.sleep(0.5)
    except:
        pass
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .nav-link:nth-child(1)").click()
  
